# Generated by Django 5.2.8 on 2026-06-25 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_review_parent_alter_review_description_and_more'),
        ('mangas', '0007_remove_author_mangas_author_mangas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mangas.chapter'),
        ),
    ]
