# Generated by Django 5.2.8 on 2025-12-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='death_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='last_published',
            field=models.DateTimeField(blank=True),
        ),
    ]
