# Generated by Django 5.2.8 on 2025-12-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0002_alter_author_death_date_alter_serie_last_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='death_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='last_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
