# Generated by Django 5.2.8 on 2026-01-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0003_alter_author_death_date_alter_serie_last_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='serie',
            name='genre',
            field=models.CharField(blank=True, choices=[('SH', 'shonen'), ('SE', 'seinen'), ('SHO', 'shojo')], null=True),
        ),
    ]
