# Generated by Django 5.2.8 on 2026-02-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0004_serie_cover_serie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='genre',
            field=models.CharField(blank=True, choices=[('shonen', 'shonen'), ('seinen', 'seinen'), ('shojo', 'shojo')], null=True),
        ),
    ]
