# Generated by Django 5.2.8 on 2026-03-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0005_author_image_alter_serie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='authors/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='series/%Y/%m/%d/'),
        ),
    ]
