# Generated by Django 5.2.8 on 2026-06-16 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0006_alter_author_image_alter_serie_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='mangas',
        ),
        migrations.AddField(
            model_name='author',
            name='mangas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='mangas.serie'),
        ),
    ]
