# Generated by Django 5.2.8 on 2026-07-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0007_remove_author_mangas_author_mangas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='mangas',
        ),
        migrations.AddField(
            model_name='author',
            name='mangas',
            field=models.ManyToManyField(related_name='mangas', to='mangas.serie'),
        ),
    ]
